export const SET_LOG_STATUS = 'SET_LOG_STATUS';
export const SET_USER = 'SET_USER';
export const SET_ESTATE = 'SET_ESTATE';
export const SET_DEFAULT = 'SET_DEFAULT';
export const SELECTED_CITY = 'SELECTED_CITY';
export const SELECTED_OPERATION = 'SELECTED_OPERATION';
export const SELECTED_DEPARTAMENT = 'SELECTED_DEPARTAMENT';
export const SELECTED_WORD = 'SELECTED_WORD';
export const SET_DEPARTAMENT_ESTATE_FORM = 'SET_DEPARTAMENT_ESTATE_FORM';
export const SET_CITY_ESTATE_FORM = 'SET_CITY_ESTATE_FORM';
export const SET_ESTATE_TYPE = 'SET_ESTATE_TYPE';
export const SET_CITIES_ID = 'SET_CITIES_ID';
export const SET_DEPARTAMENTS_ID = 'SET_DEPARTAMENTS_ID';
export const SET_ORDER = 'SET_ORDER';

export const InputTypes = {
    CHECKBOX: 'CHECKBOX',
    TEXTBOX: 'TEXTBOX',
    MIN_MAX: 'MIN_MAX'    
}

export const Orientation = {
    VERTICAL: 0,
    HORIZONTAL: 1
    
}

