export const SET_LOG_STATUS = 'SET_LOG_STATUS';
export const SET_USER = 'SET_USER';
export const SET_ESTATE = 'SET_ESTATE';
export const SET_DEFAULT = 'SET_DEFAULT';
export const SELECTED_CITY = 'SELECTED_CITY';
export const SELECTED_OPERATION = 'SELECTED_OPERATION';
export const SELECTED_DEPARTAMENT = 'SELECTED_DEPARTAMENT';
export const SELECTED_WORD = 'SELECTED_WORD';
export const SET_DEPARTAMENT_ESTATE_FORM = 'SET_DEPARTAMENT_ESTATE_FORM';
export const SET_CITY_ESTATE_FORM = 'SET_CITY_ESTATE_FORM';
export const SET_ESTATE_TYPE = 'SET_ESTATE_TYPE';

